src/components/body/Body.svelte
=> NamDD.IN-LP/style-noti-node-sale restyle noti node sale

src/components/body/Body.svelte, src/components/header/Header.svelte
fix handle click tab on header
=> NamDD.IN-LP-1143/style/relayout-header fix handle click tab on header

src/components/header/Header.svelte
=> NamDD.IN-1148/feat/noti-campaign-ui add noti about campaign

src/components/header/Header.svelte
=> NamDD.IN-1148/feat/noti-campaign-ui change style text noti

src/components/header/Header.svelte
=> NamDD.IN-1148/feat/noti-campaign-ui more restyle text content

src/components/header/Header.svelte
change gpu link download to linux
=> NamDD.IN/hot-update/change-link-download-macos change gpu link download to linux

src/components/header/Header.svelte
=> NamDD.IN-1143/style/restyle-header change ui header bar

src/components/body/Map.svelte
=> UpdareUiMap

src/components/body/Body.svelte
=> NamDD.IN/feat/optimize-landing-page add restyle node sale

src/components/header/Header.svelte
=> NamDD.IN-1161/style/restyle-header fix some style header

src/components/body/Events.svelte
=> NamDD.IN-1157/style-restyle-event-mobile restyle events screen mobile

src/components/header/Header.svelte
=> NamDD.IN/hot-fix/update-text-download updatex window to windows

src/components/header/Header.svelte
=> NamDD.IN/hot-fix/update-text-download fix style of download button

src/components/header/Header.svelte
=> NamDD.IN-1148/feat/noti-campaign-ui change day left campaign

src/components/body/Events.svelte
change style events title and responsive
=> NamDD.IN-1156/style/restyle-events-title change style events title and responsive

src/components/body/Body.svelte
=> NamDD.IN-1172/feat/new-partner-design change new partner design

src/components/body/Body.svelte, src/components/body/Events.svelte, src/components/body/IndustrieUI.svelte
=> NamDD.IN-1175/style/restyle-text change font family text

src/components/body/Events.svelte
=> NamDD.IN-1178/style/fix-margin-event fix margin

src/components/config/api.ts
Sửa lỗi lấy thông tin node trên dev bị lỗi
=> FixCallApiDev

src/components/body/Body.svelte
change color border events screen
=> NamDD.IN-1180/style/fix-style-events change color border events screen

src/components/body/Body.svelte
=> NamDD.IN-1181/style/fix-gap-events change space between content

src/components/body/Events.svelte
change how to show title on only 2 line
=> NamDD.IN-1187/style/show-title-events change how to show title on only 2 line

src/components/body/Events.svelte
=> NamDD.IN-1189/feat/add-link-events add more link for event

src/components/header/Header.svelte
relayout header bar and add whitepaper button
=> NamDD.IN-1193/feat/layout-headerbar relayout header bar and add whitepaper button

src/components/body/Body.svelte
fix z-index of btn Buy Now node sale
=> NamDD.IN-1198/style/fix-btn-buy-now fix z-index of btn Buy Now node sale

src/components/body/Body.svelte, src/components/body/MapLaptop.svelte, src/components/body/MapMobile.svelte, src/components/body/MapTablet.svelte
=> KienDT.PN-1200 Responsive Map

src/components/body/Body.svelte
…de sale mobilechange padding and height node sale mobile
=> NamDD.IN-1199/style/responsive-node-sale change padding and height node sale mobile

src/components/body/Events.svelte
increase space with above content
=> NamDD.IN-1203/style/fix-style-events increase space with above content

src/components/body/BackgroundCard.svelte, src/components/body/Body.svelte
change space with other content
=> NamDD.IN-12005/style/fix-style-partners change space with other content

src/components/body/Map.svelte, src/components/body/MapLaptop.svelte, src/components/body/MapMobile.svelte, src/components/body/MapTablet.svelte
=> FixHeightMap

src/components/body/Body.svelte, src/components/header/Header.svelte
=> NamDD.IN-1199/style/update some style

src/components/footer/Footer.svelte
=> NamDD.IN/hot-fix/relayout-footer relayout footer

src/components/header/Header.svelte
fix days left on mobile version
=> hot-fix/fix-days-left-mobile fix dayss left on mobile version

src/components/header/Header.svelte
update more responsive begin content
=> NamDD.IN-1170/update/begin-content update more responsive begin content

src/components/body/CardItem.svelte
=> Change color border

src/components/body/IndustrieUI.svelte
=> Industries on Tablet

src/components/body/Body.svelte
=> NamDD.IN-1213/style/fix-responsive-node-sale responsive for node sale

src/components/body/Body.svelte
responsive for screen 768-1023
=> NamDD.IN-1215/style/responsive-partners responsive for screen 768-1023

src/components/body/Body.svelte
responsive node sale for screen tablet
=> NamDD.IN-1216/style/responsive-node-sale responsive node sale for screen tablet

src/components/body/Events.svelte
responsive events for screen from 1024px to 1280px
=> NamDD.IN-1217/style/responsive-events responsive events for screen from 1024px to 1280px

src/components/footer/Footer.svelte
responsive for screen 768px to 1024px
=> NamDD.IN-1218/style/responsive-footer responsive for screen 768px to 1024px

src/components/body/Body.svelte
fix width popup and content popup node sale
=> NamDD.IN-1212/style/fix-style-popup-nodesale fix width popup and content popup node sale

src/components/header/Header.svelte
=> hot-update/change-countdown change countdown to 25/9

src/components/register/BodyRegister.svelte
update time and noti leaderboard
=> hot-update/update-content-register update time and noti leaderboard

src/components/header/Header.svelte
=> hot-fix/fix-download-mobile change content mobile

src/components/ModalNodeSale.svelte
update button buy node sale on popup
=> hot-fix/update button buy node sale on popup

src/components/header/Header.svelte
tienmvv.feature/hot-fix-transition-bar
=> tienmvv.feature/hot-fix-transition-bar

src/components/header/Header.svelte
tienmvv.feature/add blog to menu
=> tienmvv.feature/add blog to menu
